[[docs]]
  name = "Getting Started"
  weight = 10
  identifier = "getting-started"
  url = "/docs/getting-started/"



[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"


# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Documentation"
  weight = 20
  identifier = "documentation"
  url = "/docs/getting-started/introduction/"


[[main]]
  name = "Getting Started"
  url = "/docs/getting-started/where-to-start/"
  weight = 10



[[main]]
  name = "Platform reference"
  weight = 30
  identifier = "platform"
  url = "https://getdoks.org/tutorial/introduction/"
  parent = "documentation"

[[main]]
  name = "Developer's reference"
  weight = 40
  identifier = "dev-reference"
  url = "https://getdoks.org/tutorial/introduction/"
  parent = "documentation"

[[main]]
  name = "Extending the platform"
  weight = 50
  identifier = "tutorial"
  url = "https://getdoks.org/tutorial/introduction/"
  parent = "documentation"




[[social]]
  name = "Home"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" viewBox=\"0 0 20 20\"><path fill=\"none\" stroke=\"black\" stroke-width=\"1.5\" d=\"M18.5,10.5l-1.21,1.21v6.29h-5v-4h-4v4h-5v-6.29l-1.21-1.21L10,3.5l8.5,7Z\"/></svg>"
  url = "https://www.slingr.io/"
  weight = 10





# [[footer]]
 #  name = "Privacy"
  # url = "/privacy-policy/"
   #weight = 10
